local eldar_desc = [[Placeholder
Desc]]
local galadriel_desc = [[Placeholder
Desc]]
local yavanna_desc = [['In the form of the woman she is tall, and robed in green, but at times she takes other shapes. Some there are who have seen her standing like a tree under heaven, crowned with the Sun, and from all its branches there spilled a golden dew upon the barren earth.']]
local ents_desc = [[Placeholder
Desc]]
local ulmo_desc = [[Placeholder
Desc]]
local gwaith_desc = [[Placeholder
Desc]]
local orome_desc = [[Placeholder
Desc]]
local tulkas_desc = [[Placeholder
Desc]]
local eye_desc = [[Placeholder
Desc]]
local horde_desc = [[Placeholder
Desc]]
local mining_op_desc = [[Placeholder
Desc]]
local anor_desc = [[Placeholder
Desc]]
local mengood_0_desc = [[Placeholder
Desc]]
local nazgul_0_desc = [[Nine he gave to Mortal Men, proud and great, and so ensnared them. Long ago they fell under the dominion of the One, and they became Ringwraiths, shadows under his great Shadow, his most terrible servants. Long ago. It is many a year since the Nine walked abroad. Yet who knows? As the Shadow grows once more, they too may walk again]]
local gondor_2_desc = [["One day, our paths will lead us there. And the tower guard shall take up the call: 'The Lords of Gondor have returned!'" - Boromir]]

EUR_EVENTS = {
    ["ireland"] = {
        [0] = {
            name = "Mirror of Galadriel",
            desc = galadriel_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = 6,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Our lady's efforts are needed in the defence of Lorien, reclaim Amon Lanc to unlock.",
            sound = "upowersup",
        },
        [1] = {
            name = "Yavanna's Blessing",
            desc = yavanna_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Awakening of the Trees",
            desc = ents_desc,
            func = nil,
            cost = 5000,
            cooldown = 60,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Reclaim Fangorn to call upon powerful Ent allies.",
            sound = "upowersup",
        },
        [3] = {
            name = "Light of the Eldar",
            desc = eldar_desc,
            func = nil,
            cost = 2500,
            cooldown = 30,
            active_cooldown = 0,
            duration = 10,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["mongols"] = {
        [0] = {
            name = "Mirror of Galadriel",
            desc = galadriel_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = 6,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Yavanna's Union and Amon Lanc required.",
            sound = "upowersup",
        },
        [1] = {
            name = "Yavanna's Blessing",
            desc = yavanna_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Spirit of Oromë",
            desc = orome_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = 6,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [3] = {
            name = "Light of the Eldar",
            desc = eldar_desc,
            func = nil,
            cost = 2500,
            cooldown = 30,
            active_cooldown = 0,
            duration = 10,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["saxons"] = {
        [0] = {
            name = "Gwaith-i-Mírdain",
            desc = gwaith_desc,
            func = nil,
            cost = 15000,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Gwaith-i-Mírdain locked, retake Ost-in-Edhil.",
            sound = "upowersup",
        },
        [1] = {
            name = "Celebration of Tulkas",
            desc = tulkas_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Yavanna's Blessing",
            desc = yavanna_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [3] = {
            name = "Light of the Eldar",
            desc = eldar_desc,
            func = nil,
            cost = 2500,
            cooldown = 30,
            active_cooldown = 0,
            duration = 10,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["denmark"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [1] = {
            name = "Yavanna's Blessing",
            desc = yavanna_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Gwaith-i-Mírdain",
            desc = gwaith_desc,
            func = nil,
            cost = 15000,
            cooldown = 50,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Gwaith-i-Mírdain locked until turn 50.",
            sound = "upowersup",
        },
        [3] = {
            name = "Light of the Eldar",
            desc = eldar_desc,
            func = nil,
            cost = 2500,
            cooldown = 30,
            active_cooldown = 0,
            duration = 10,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["milan"] = {
        [0] = {
            name = "Anor Stone",
            desc = anor_desc,
            func = nil,
            cost = 2500,
            cooldown = 25,
            active_cooldown = 0,
            duration = 6,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [1] = {
            name = "Repopulate Lands",
            desc = mengood_0_desc,
            func = nil,
            cost = 2000,
            cooldown = 25,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Oath of Cirion",
            desc = mengood_0_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["sicily"] = {
        [0] = {
            name = "Anor Stone",
            desc = anor_desc,
            func = nil,
            cost = 2500,
            cooldown = 25,
            active_cooldown = 0,
            duration = 6,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [1] = {
            name = "Repopulate Lands",
            desc = mengood_0_desc,
            func = nil,
            cost = 2000,
            cooldown = 25,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Oath of Eorl",
            desc = mengood_0_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [3] = {
            name = "Lords of Gondor",
            desc = gondor_2_desc,
            func = nil,
            cost = 2000,
            cooldown = 25,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["turks"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [1] = {
            name = "Repopulate Lands",
            desc = mengood_0_desc,
            func = nil,
            cost = 2000,
            cooldown = 25,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["russia"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["scotland"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [1] = {
            name = "Repopulate Lands",
            desc = mengood_0_desc,
            func = nil,
            cost = 2000,
            cooldown = 25,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["byzantium"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["timurids"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["portugal"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["aztecs"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["teutonic_order"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["spain"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["khand"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["venice"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["norway"] = {
        [0] = {
            name = "Mining Operations",
            desc = mining_op_desc,
            func = nil,
            cost = 5000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["hungary"] = {
        [0] = {
            name = "Mining Operations",
            desc = mining_op_desc,
            func = nil,
            cost = 5000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["moors"] = {
        [0] = {
            name = "Mining Operations",
            desc = mining_op_desc,
            func = nil,
            cost = 5000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["england"] = {
        [0] = {
            name = "The Great Eye",
            desc = eye_desc,
            func = nil,
            cost = 0,
            cooldown = 10,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "",
        },
        [1] = {
            name = "Call Horde",
            desc = horde_desc,
            func = nil,
            cost = 5000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "",
        },
    },
    ["normans"] = {
        [0] = {
            name = "The Great Eye",
            desc = eye_desc,
            func = nil,
            cost = 0,
            cooldown = 10,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "",
        },
        [1] = {
            name = "Call Horde",
            desc = horde_desc,
            func = nil,
            cost = 5000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "",
        },
    },
    ["poland"] = {
        [0] = {
            name = "The Great Eye",
            desc = eye_desc,
            func = nil,
            cost = 0,
            cooldown = 10,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "",
        },
        [1] = {
            name = "Call Horde",
            desc = horde_desc,
            func = nil,
            cost = 5000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "",
        },
    },
    ["hre"] = {
        [0] = {
            name = "The Great Eye",
            desc = eye_desc,
            func = nil,
            cost = 0,
            cooldown = 10,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "",
        },
        [1] = {
            name = "Call Horde",
            desc = horde_desc,
            func = nil,
            cost = 5000,
            cooldown = 30,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "",
        },
    },
    ["gundabad"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["france"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = ulmo_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
}
