local elves_0_desc = [[Placeholder
Desc]]
local lorien_0_desc = [[Placeholder
Desc]]
local lorien_1_desc = [['In the form of the woman she is tall, and robed in green, but at times she takes other shapes. Some there are who have seen her standing like a tree under heaven, crowned with the Sun, and from all its branches there spilled a golden dew upon the barren earth.']]
local lorien_2_desc = [[Placeholder
Desc]]
local lindon_0_desc = [[Placeholder
Desc]]
local imladris_0_desc = [[Placeholder
Desc]]
local wr_0_desc = [[Placeholder
Desc]]
local imladris_1_desc = [[Placeholder
Desc]]

EUR_EVENTS = {
    ["ireland"] = {
        [0] = {
            name = "Mirror of Galadriel",
            desc = lorien_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = 6,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Our lady's efforts are needed in the defence of Lorien, reclaim Amon Lanc to unlock.",
            sound = "upowersup",
        },
        [1] = {
            name = "Yavanna's Blessing",
            desc = lorien_1_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Awakening of the Trees",
            desc = lorien_2_desc,
            func = nil,
            cost = 5000,
            cooldown = 60,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Reclaim Fangorn to call upon powerful Ent allies.",
            sound = "upowersup",
        },
        [3] = {
            name = "Light of the Eldar",
            desc = elves_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 30,
            active_cooldown = 0,
            duration = 10,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["mongols"] = {
        [0] = {
            name = "Mirror of Galadriel",
            desc = lorien_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = 6,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Yavanna's Union and Amon Lanc required.",
            sound = "upowersup",
        },
        [1] = {
            name = "Yavanna's Blessing",
            desc = lorien_1_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Spirit of Oromë",
            desc = wr_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = 6,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [3] = {
            name = "Light of the Eldar",
            desc = elves_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 30,
            active_cooldown = 0,
            duration = 10,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["saxons"] = {
        [0] = {
            name = "Gwaith-i-Mírdain",
            desc = imladris_1_desc,
            func = nil,
            cost = 15000,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Gwaith-i-Mírdain locked, retake Ost-in-Edhil.",
            sound = "upowersup",
        },
        [1] = {
            name = "Celebration of Tulkas",
            desc = imladris_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Yavanna's Blessing",
            desc = lorien_1_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [3] = {
            name = "Light of the Eldar",
            desc = elves_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 30,
            active_cooldown = 0,
            duration = 10,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
    ["denmark"] = {
        [0] = {
            name = "Ulmo's Favour",
            desc = lindon_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 40,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [1] = {
            name = "Yavanna's Blessing",
            desc = lorien_1_desc,
            func = nil,
            cost = 2000,
            cooldown = 30,
            active_cooldown = 0,
            duration = 5,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
        [2] = {
            name = "Gwaith-i-Mírdain",
            desc = imladris_1_desc,
            func = nil,
            cost = 15000,
            cooldown = 50,
            active_cooldown = 0,
            duration = nil,
            active_duration = 0,
            image = nil,
            unlocked = false,
            locked_desc = "Gwaith-i-Mírdain locked until turn 50.",
            sound = "upowersup",
        },
        [3] = {
            name = "Light of the Eldar",
            desc = elves_0_desc,
            func = nil,
            cost = 2500,
            cooldown = 30,
            active_cooldown = 0,
            duration = 10,
            active_duration = 0,
            image = nil,
            unlocked = true,
            sound = "upowersup",
        },
    },
}
